### ISSUE TITLE
Template "Image extracted" not properly extended

### ISSUE THREAD

**Issue by Aschroet** [danmichaelo/croptool#102]
When extracting more than two images from one source image the template _Image extracted_ is not properly extended, example:

- https://commons.wikimedia.org/w/index.php?title=File:FMIB_32646_Magnified.jpeg&diff=270147417&oldid=270147388
-  https://commons.wikimedia.org/w/index.php?title=File:FMIB_32646_Magnified.jpeg&diff=270147502&oldid=270147453

The parameters for extracted imagines should be counted up, i. e. _3=_ _4=_

**Comment by sikanderiqbal** [comment]
I think this resolves it: #103

**Comment by Aschroet** [comment]
When will it be productive? I ask because it happened again: https://commons.wikimedia.org/w/index.php?title=File:FMIB_32646_Magnified.jpeg&diff=270148587&oldid=270148530

**Comment by danmichaelo** [comment]
Deployed now! Sorry for the problems it caused!
