### ISSUE TITLE
Failure for a djvu page

### ISSUE THREAD

**Issue by alexbrollo** [danmichaelo/croptool#104]
Entering into CropTool with this url:

https://tools.wmflabs.org/croptool/?title=Leonardo_prosatore.djvu&page=7

I get this error message:
Command not found: "ddjvu -page='7' -format=tiff '/data/project/croptool/public_html/files/bb2fe6dee30ff2caefc752e72a737b5e4eb24e6e.djvu' '/data/project/croptool/public_html/files/bb2fe6dee30ff2caefc752e72a737b5e4eb24e6e.djvu.page7.jpg.tiff' 2>&1"

I hope that the issue is simple to fix.... I can't live without CropTool!

**Comment by danmichaelo** [comment]
Ouch, I tried migrating to Kubernetes, but forgot the dependence on ddjvu. Rolled back, should work now.

**Comment by alexbrollo** [comment]
As you guess from feedback of the tool if any, all it.wikisource suffers
from  "CropTool  addiction" :-)  so any failure of the tool is followes by
a hard alarm.
We developed too a gadget that adds a draft, but good code for images
coming from CropTool, using the default CropTool derived default name, so
that adding an image to a page code is a matter of a few clicks :-)

Alex

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-14 14:52 GMT+01:00 Dan Michael O. Heggø <notifications@github.com>:
