### ISSUE TITLE
URL encoding for file link after upload

### ISSUE THREAD

**Issue by sikanderiqbal** [danmichaelo/croptool#108]
File name includes: `Mohammad Akram Khpalwāk`

Post upload, link to Wikimedia Commons shows as: `<a target="_blank" href="//commons.wikimedia.org/wiki/File:Mohammad%20Akram%20Khpalw%u0101k%20and%20Karim%20Khalili%20with%20John%20Sullivan%20-%202018%20%2839297711844%29.jpg">`

Clicking this shows a 400 Bad Request: https://commons.wikimedia.org/wiki/File:Mohammad%20Akram%20Khpalw%u0101k%20and%20Karim%20Khalili%20with%20John%20Sullivan%20-%202018%20%2839297711844%29.jpg

This should be: `https://commons.wikimedia.org/wiki/File:Mohammad_Akram_Khpalw%C4%81k_and_Karim_Khalili_with_John_Sullivan_-_2018_(39297711844).jpg` ([commons](https://commons.wikimedia.org/wiki/File:Mohammad_Akram_Khpalw%C4%81k_and_Karim_Khalili_with_John_Sullivan_-_2018_(39297711844).jpg))

**Comment by danmichaelo** [comment]
Thanks for reporting! I need some help to identify *which* link you refer to though. After uploading, you should get a link in the text "You can now review the result", but when I tested now, the encoding there seemed to work fine (at test wikipedia): `<a href="https://test2.wikipedia.org/wiki/File:Mohammad_Akram_Khpalw%C4%81k_and_Karim_Khalili_with_John_Sullivan_-_2018_(39297711844)_-_test.jpg">review the result</a>`. Is there some other link? If it's the same link, could you share your browser and version?

**Comment by sikanderiqbal** [comment]
Yikes, nevermind, I goofed up and posted in the wrong project!

This issue is for Flickr2Commons. Sorry about that :)
