### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Jeff-Gdot** [danmichaelo/croptool#112]
This was reported at [https://commons.wikimedia.org/wiki/Commons_talk:CropTool#502_Bad_Gateway](https://commons.wikimedia.org/wiki/Commons_talk:CropTool#502_Bad_Gateway) and I have confirmed it at [https://tools.wmflabs.org/croptool/](https://tools.wmflabs.org/croptool/).

**Comment by danmichaelo** [comment]
Thanks for reporting!

**Comment by danmichaelo** [comment]
Restarted.

It happens a bit too often now though :( Need to check with the Toolforge admins if there's something to do about it, perhaps move to a separate vm.
