### ISSUE TITLE
Just a moment... forever

### ISSUE THREAD

**Issue by nicolas-raoul** [danmichaelo/croptool#113]
When loading https://tools.wmflabs.org/croptool/ a screen with untranslated strings and red areas is shown for less than a second, then this screen is shown:

![screenshot from 2018-06-29 14-55-57](https://user-images.githubusercontent.com/99590/42075592-927b2060-7bac-11e8-93a0-64ec424004db.png)

... and it stays like this forever.
Tested in both recent Firefox and Chromium.

**Comment by revi** [comment]
Same here, macOS 10.13, newest Safari and Google Chrome 67.0.3396.99 (64bit)

**Comment by danmichaelo** [comment]
Will restart it in a few minutes, just trying to gather some data first. Lots of hanging connections (https://tools.wmflabs.org/croptool/server-statistics), but not sure why it happens from time to time.

```
fastcgi.active-requests: 184
fastcgi.backend.0.0.connected: 207
fastcgi.backend.0.0.died: 0
fastcgi.backend.0.0.disabled: 0
fastcgi.backend.0.0.load: 92
fastcgi.backend.0.0.overloaded: 0
fastcgi.backend.0.1.connected: 572
fastcgi.backend.0.1.died: 0
fastcgi.backend.0.1.disabled: 0
fastcgi.backend.0.1.load: 92
fastcgi.backend.0.1.overloaded: 0
fastcgi.backend.0.load: 184
fastcgi.requests: 779
```

**Comment by danmichaelo** [comment]
Restarted. And I've been seeking help on IRC to try to figure out the underlying issue.

**Comment by danmichaelo** [comment]
Added a Phabricator issue as well to track this: https://phabricator.wikimedia.org/T198503
