### ISSUE TITLE
Croptool down

### ISSUE THREAD

**Issue by osirisgreene** [danmichaelo/croptool#114]
Looks like the server needs to be restarted again, it's been down for at least a few hours now...

**Comment by Jeff-Gdot** [comment]
The last edit it tagged was 16:24, 7 July 2018 (UTC), 22 hours ago.

**Comment by danmichaelo** [comment]
Sorry for the slow response. I wish I could have a script that automatically restarted the server when it locks up, but it doesn't seem to be possible. See also https://phabricator.wikimedia.org/T198503
