### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Jeff-Gdot** [danmichaelo/croptool#116]
Stuck on "just a moment" for several minutes, needs to be restarted per [https://commons.wikimedia.org/w/index.php?title=Commons_talk:CropTool&diff=313415931&oldid=313368484](https://commons.wikimedia.org/w/index.php?title=Commons_talk:CropTool&diff=313415931&oldid=313368484) .

**Comment by danmichaelo** [comment]
Done. But my response rate in these cases is not good enough.. Need to find a way to automate it!

**Comment by danmichaelo** [comment]
Tracked at https://phabricator.wikimedia.org/T198503
