### ISSUE TITLE
Don't copy FlickreviewR template

### ISSUE THREAD

**Issue by wafflefin** [danmichaelo/croptool#117]
If there is a FlickreviewR template from the FlickreviewR bot, you get an abusefilter-warning error when uploading a new file. This is a similar issue to #96.

An example can be found in the files in the category: https://commons.wikimedia.org/wiki/Category:Flickr_images_reviewed_by_FlickreviewR_2

**Comment by danmichaelo** [comment]
Thanks, should be fixed now!
