### ISSUE TITLE
Cosmetic issue

### ISSUE THREAD

**Issue by Aschroet** [danmichaelo/croptool#122]
Would be really nice to have a cosmetic change when the CropTool creates the information template. Before and after ther other_versions parameter should be a newline. Expected change:
https://commons.wikimedia.org/w/index.php?title=&type=revision&diff=328855565&oldid=259713911

**Comment by danmichaelo** [comment]
Thanks for reporting! In this case, the newline was eaten when the otrs template was removed. When removing templates and categories, it's sometimes necessary to remove surrounding linebreaks to avoid double linebreaks being left, but I have now improved the code so it's a bit smarter about it :)
