### ISSUE TITLE
Incomplete image loading

### ISSUE THREAD

**Issue by danmichaelo** [danmichaelo/croptool#123]
Reported on twitter: https://twitter.com/1Veertje/status/1068117833022869504

I'm not sure if curl throws an exception if the amount data received does not match the content-length header, can check.

**Comment by VDK** [comment]
[Ben Thompson image](https://tools.wmflabs.org/croptool/?title=Ben_Thompson_-_Innholdprodusentens_d%C3%B8d_og_mulige_gjenoppstandelse_-_NMD_2016_(26890581672).jpg)
[Finn Graff](https://tools.wmflabs.org/croptool/?title=NMD_Fordypning-_Vinner_av_den_store_journalistprisen_-_NMD_2018_(27997897538).jpg)
[Harald Stanghelle](https://tools.wmflabs.org/croptool/?title=NMD_%C3%85pning_Media_City_Bergen_2018_(27040320997).jpg)

The images that loaded incompletely earlier today still do so here.

**Comment by danmichaelo** [comment]
Thanks for the links! CropTool caches the images serverside for some time, actually for 10 hours, which is a bit longer than necessary :) I purged the cache now and reduced the cache time to 1 hour.

**Comment by danmichaelo** [comment]
Switched to using curl for downloading images from Commons and added a test for the content-length header now. If, for some reason, an image is incompletely downloaded, it should throw it away and show an error so you can retry by refreshing the browser. That's the theory at least :)

**Comment by VDK** [comment]
these NMD pictures have this problem frequently.

when the picture is unable to load in CropTool, then it is also the case that the image will load as incompletely if you open it up in the Media Viewer and then request to download it at the full resolution.

This is the link the Media Viewer uses: 
https://upload.wikimedia.org/wikipedia/commons/1/1e/Medieunders%C3%B8kelsen_2018-_Dette_vil_ungdommen_ha_-_NMD_2018_%2840108142260%29.jpg?download

The photo does load completely by following the "download" > "full resolution" link in the [Stockphoto gadget](https://commons.wikimedia.org/wiki/Help:Gadget-Stockphoto)

The link there is this:
https://upload.wikimedia.org/wikipedia/commons/1/1e/Medieunders%C3%B8kelsen_2018-_Dette_vil_ungdommen_ha_-_NMD_2018_%2840108142260%29.jpg

After following that link the link in the Media Viewer starts working, but CropTool still doesn't. That might be a caching issue?

**Comment by VDK** [comment]
Other files this applies to:

https://commons.wikimedia.org/wiki/File:Datoen-_En_historietime_helt_utenom_det_vanlige_-_NMD_2016_(26966062435).jpg

**Comment by pieva** [comment]
Same issue with a DjVu file that worked properly till 2 days ago
- [ok](https://commons.wikimedia.org/wiki/Category:Codifica_numerica_del_segnale_audio)
- [ko](https://tools.wmflabs.org/croptool/?title=Codifica_numerica_del_segnale_audio.djvu&page=71)

**Comment by danmichaelo** [comment]
Never mind, I did a quick test using wget now and it worked on first attempt. Since wget automatically retries the download, I think this works around the issue, but of course loading an image will take longer than normal if it has to retry several times.

**Comment by danmichaelo** [comment]
Removed the workaround since a fix for T210890 has now been deployed.
