### ISSUE TITLE
Add configuration of settings via URL query

### ISSUE THREAD

**Issue by stjohann** [danmichaelo/croptool#126]
I have a distant wish to write a script that would add a link to CropTool from images that use {{CSS image crop}} in Russian Wikipedia to facilitate some ‘crusade’ against their prevalence :-) Since they already have some kind of configuration in place, it would be helpful to have some way to provide the needed crop from the link (`&x=0&y=0&width=560`). Can this be added to the tool?

**Comment by danmichaelo** [comment]
This should be fairly easy to add, I'll probably do it.

**Comment by danmichaelo** [comment]
Finally added! It supports 

* Coordinates from edges: `&left=10&top=10&right=10&bottom=10`
* `width`/`height` in combination with `left`/`right` or , `top`/`bottom`:
  * `&left=10&top=10&width=560&height=100`
  * `&right=10&top=10&width=560&height=100`
  * ...
