### ISSUE TITLE
jpegtran exited with code 2

### ISSUE THREAD

**Issue by Jeff-Gdot** [danmichaelo/croptool#131]
I got the following while trying to crop https://commons.wikimedia.org/wiki/File:2019_Virginia_Avenue_train_tunnel_entrance.jpg :

[Error] Command "/data/project/croptool/jpeg-9a/jpegtran -copy all -crop '3024x1189+0+0' '/mnt/nfs/labstore-secondary-tools-project/croptool/public_html/files/b920c594697f84cc1a30698e1ce76b08ec330ee7.jpg' > '/mnt/nfs/labstore-secondary-tools-project/croptool/public_html/files/b920c594697f84cc1a30698e1ce76b08ec330ee7_cropped.jpg' 2>&1" exited with code 2: 2

**Comment by danmichaelo** [comment]
Hm, I think this file has some issues:

<img width="711" alt="Screenshot 2019-03-25 at 21 01 56" src="https://user-images.githubusercontent.com/434495/54950286-3f00db00-4f41-11e9-83bd-a29420a2caab.png">

Did the file look normal earlier?

**Comment by danmichaelo** [comment]
Closing due to no response, but I'm keeping #134 open, which is about the same issue.
