### ISSUE TITLE
Impossible to use croptool for one specific file

### ISSUE THREAD

**Issue by DaraNguyen** [danmichaelo/croptool#132]
Hello,

I've been having a bug since yesterday on croptool, but only for one specific file.

Steps to reproduce the bug:

- go to https://commons.wikimedia.org/wiki/File:Banville_-_%C5%92uvres,_Le_Sang_de_la_coupe,_1890.djvu
- Click "Croptool" on the left side of the screen (you must have activated the croptool gadget)

Actual Results:

- This (https://commons.wikimedia.org/wiki/File:Croptool_bug.png) screen appears for a very short time, and then you are redirected to a form about "What to crop?".
- When you enter the name of the file (File:Banville - Œuvres, Le Sang de la coupe, 1890.djvu) and click "open", nothing happens.

Expected Results:

- Normally, you directly get the interface on which you select the part of the file you want to crop.

Extra info:

- I did the same steps a few weeks ago with the same file and computer configuration, and it worked.
- I did the same steps with other random files since the problem appeared, and it worked.
- User:Yann tried the same steps with Chrome on Monobook and Windows7, and had the same issue.
- I am using the vector skin of commons, on Mozilla Firefox 60.6.0esr (32 bits), on a windows computer.

Do you know where it could come frome ?
Thanks,
Dara

**Comment by danmichaelo** [comment]
Thanks for reporting this! Cropping of DJVU files was broken.

**Comment by danmichaelo** [comment]
Should now be working. Sorry for the inconvenience

**Comment by DaraNguyen** [comment]
Thank you ! :smile:
