### ISSUE TITLE
Your IP address has been blocked automatically, because it was used by a blocked user. 

### ISSUE THREAD

**Issue by SednaBoo** [danmichaelo/croptool#135]
On this page:
[(https://tools.wmflabs.org/croptool/?title=N136_w1150_(9716017609).jpg)]
I got this error:
> Upload failed! [api] Received error: autoblocked : Your IP address has been blocked automatically, because it was used by a blocked user. 

I tried looking up my IP and didn't see any bans, but maybe I looked in the wrong place.  I am also logged in and authorized.

**Comment by jdeazy** [comment]
Yep, same here.

**Comment by danmichaelo** [comment]
Ouch, seems like the Toolforge server IP is blocked!?

**Comment by danmichaelo** [comment]
https://commons.wikimedia.org/wiki/Commons:Administrators%27_noticeboard/Blocks_and_protections#Toolforge_IPs_blocked?

**Comment by danmichaelo** [comment]
So it's fixed for this time, but CropTool was down for everyone except sysops from 2019-04-18 18:20 UTC to  2019-04-19 14:52 UTC.

I had forgot, but seems like this also happened in 2014:

https://phabricator.wikimedia.org/T68639

Seems like there isn't much progress on https://phabricator.wikimedia.org/T74501 though.

**Comment by danmichaelo** [comment]
The whitelist was just updated to cover the Toolforge IP range: https://commons.wikimedia.org/w/index.php?title=MediaWiki%3AAutoblock_whitelist&type=revision&diff=346495333&oldid=167834125

Let's hope this will prevent the same problem from happening again.

**Comment by nicolasmaia** [comment]
This is happening again for me.
