### ISSUE TITLE
Migrate to the toolforge.org domain

### ISSUE THREAD

**Issue by daylenca** [danmichaelo/croptool#149]
Support for tools.wmflabs.org domains is ending on June 30th! See https://wikitech.wikimedia.org/wiki/News/Toolforge.org for the required changes.

**Comment by Nintendofan885** [comment]
*tools.wmflabs.org

**Comment by danmichaelo** [comment]
Fixed in 12b575a5ce1a8c4651fe098e82e16a4ddc558557 and 52166b6db855fe4a8233c3ac4f36941f15520a93 (before Summer, but forgot to commit)
