### ISSUE TITLE
CropTool messes with color

### ISSUE THREAD

**Issue by Glearand** [danmichaelo/croptool#169]
When I tried to crop [File:2020-02-13 Jens Brandenburg (KPFC) 02.jpg](https://commons.wikimedia.org/wiki/File:2020-02-13_Jens_Brandenburg_(KPFC)_02.jpg) which looks like this:
<img src="https://user-images.githubusercontent.com/95657954/144930826-a958a535-42bf-4fa8-ac62-359a5a6a9229.jpg" width=50% height=50%>
at least the preview looked like this:
<img src="https://user-images.githubusercontent.com/95657954/144932290-fd83b22c-9d47-410b-ab61-72b36996d2c6.jpg" width=50% height=50%>
so CropTool messed up the colors pretty badly.
I couldn't figure out what's special about this image and for obvious reasons, I didn't try uploading it.

**Comment by Jonteemil** [comment]
See actual result at https://commons.wikimedia.org/wiki/File:2020-02-13_Jens_Brandenburg_(KPFC)_02_(test).jpg which actually looks fine so it seems it just is the preview whose colors are messed with.

**Comment by danmichaelo** [comment]
Color profiles were indeed stripped from thumbnails, which caused incorrect colors for non-sRGB images. Should be fixed now!
