### ISSUE TITLE
Croptool not working for books

### ISSUE THREAD

**Issue by bodhisattwawiki** [danmichaelo/croptool#174]
Just recently noticed that croptool is not working for books. For example for this page - https://bn.wikisource.org/s/1rtb , when I go to https://croptool.toolforge.org/?title=বরেন্দ্র_রন্ধন.djvu&page=48  , it gives me this message - 

> Command not found: "ddjvu -page='48' -format=tiff '/data/project/croptool/public_html/files/fe4eae4fb67d7b9baee7466945e7a4970de96b72.djvu' '/data/project/croptool/public_html/files/fe4eae4fb67d7b9baee7466945e7a4970de96b72.djvu.page48.jpg.tiff' 2>&1"

**Comment by samwilson** [comment]
Also failing for PDFs: "Command not found: gs" ([e.g.](https://croptool.toolforge.org/?site=commons.wikimedia.org&title=test.pdf))

**Comment by wikigamaliel** [comment]
Also having the same problem with .djvu files.

**Comment by Jonteemil** [comment]
I'm not able to open any TIFF file in CropTool either, examples are here: https://commons.wikimedia.org/wiki/Special:MIMESearch?mime=image%2Ftiff

> Command not found: "convert '/data/project/croptool/public_html/files/94f70812509c7593b55c8891d48bbdc5f3151027.tiff[0]' '/data/project/croptool/public_html/files/94f70812509c7593b55c8891d48bbdc5f3151027.tiff.page1.tiff' 2>&1"

**Comment by pigsonthewing** [comment]
Failing for jpg files, too.

**Comment by danmichaelo** [comment]
Sorry for the delay! The `mwoauth-invalid-authorization` issue should be fixed now. Will investigate the djvu issue, need to get the ddjvu binary working with kubernetes

**Comment by danmichaelo** [comment]
The djvu issue turned out to be a bit harder. Spent a few hours trying to compile stuff inside containers, will get back to it soon.

**Comment by danmichaelo** [comment]
No luck. The ImageMagick binary built in `ruby27` failed in the `php7.4` image:

    /data/project/croptool/bin/magick
    /data/project/croptool/bin/magick: error while loading shared libraries: libXt.so.6: cannot open shared object file: No such file or directory

and there's no compilers in the `php7.4` image. Seems like I need help from wikimedia-cloud. Will continue tomorrow.

**Comment by danmichaelo** [comment]
Seems like it's not possible to really run the tool with the new kubernetes engine yet, so I had to move back to the old engine. Hopefully, everything is now working normally again, let me know if not!
