### ISSUE TITLE
Add option to crop to a fixed ratio

### ISSUE THREAD

**Issue by danmichaelo** [danmichaelo/croptool#18]
As suggested [here](//commons.wikimedia.org/wiki/Commons_talk:CropTool#Additional_functions).

**Comment by FlominatorTM** [comment]
Yes, that would really help a lot. Cropbot provides it, maybe you can "borrow" the code from there :)

**Comment by FlominatorTM** [comment]
Maybe at least displaying the current aspect ratio in order to be able to do it manually?

**Comment by danmichaelo** [comment]
Finally got around to add this. Does the current options cover what you need?

**Comment by FlominatorTM** [comment]
Yay. You're my hero of the day, thanks!

Minor minor detail: when ratio being 16:9, the input fields are a little "tight" ...

**Comment by danmichaelo** [comment]
You mean they should be a little wider? What browser/os are you on?

**Comment by FlominatorTM** [comment]
Had a look on it. It only happens, when zooming in - so it's not that bad. Am using FF 41.0.1
![zoomed](https://cloud.githubusercontent.com/assets/12448283/10495422/1031f1ac-72bc-11e5-8c45-23ddfb1e4ac0.png)

**Comment by danmichaelo** [comment]
Aha, I've never actually tested zooming before :) But for some reason I can't reproduce it in FF 41.0.1 neither on Win nor Mac.. so I think I'll just leave it like it is for now.
