### ISSUE TITLE
Feature Request: Option to remove watermark tag

### ISSUE THREAD

**Issue by trlkly** [danmichaelo/croptool#34]
While not always the case, sometimes we remove watermarks via cropping, as long as no information or aesthetic value is lost. (This is especially true when it's part of the "border.") It would be nice if CropTool could automatically remove that tag, too.

I say to make it optional in case the crop doesn't remove the watermark.

**Comment by danmichaelo** [comment]
Deployed, and seems to work fine: https://commons.wikimedia.org/w/index.php?title=File%3ALancia_delta_1.6_GTie_engine_2.jpg&type=revision&diff=162892937&oldid=162892935
