### ISSUE TITLE
Feature Request: PNG support (and possibly GIF)

### ISSUE THREAD

**Issue by trlkly** [danmichaelo/croptool#35]
You already have bitmap cropping, so I would think it wouldn't be too hard to support other image formats. Just check them for settings before decompression and use those same settings to re-encode them back. Optimization would not be necessary anymore than it's used for thumbnails.

PNG at the very least should be supported. There are a lot of PNGs in the need-to-be-cropped categories. Non-animaged GIFs would probably be easy, but not entirely necessary. If you could throw in animated GIF, that would be amazing.

I assume you use ImageMagick to do the "precise crops," and it already supports both formats out of the box. So I wouldn't think it would be much work. (If you don't use ImageMagick, that would be what I would suggest for these other formats.)

**Comment by Rezonansowy** [comment]
+1

**Comment by danmichaelo** [comment]
Let me know if you run into any issues – I've only tested with a few files

**Comment by danmichaelo** [comment]
Hm, cropping of animated GIF files works in my local development environment (`6.9.1-10 Q16 x86_64 2015-07-26`), but not on Tool Labs precise (`ImageMagick 6.6.9-7 2014-03-06 Q16`)…

**Comment by danmichaelo** [comment]
Solved by calling the `convert` command line tool directly instead of using the php imagick interface.
