### ISSUE TITLE
Watermark tag not removed

### ISSUE THREAD

**Issue by LTeles** [danmichaelo/croptool#47]
Hi!

I had to manually remove watermark tag as CropTool didn't do it automatically.

https://commons.wikimedia.org/w/index.php?title=File%3AFloor_%28Revamp%29_em_S%C3%A3o_Paulo_%281%29.jpg&type=revision&diff=161994776&oldid=161994750

Regards.

**Comment by danmichaelo** [comment]
I'm not sure if it's a good idea to have CropTool *always* remove this, since there might be cases where you do a crop, but can't remove the watermark. But I can add a checkbox (perhaps even checked by default) to remove {{watermark}}

**Comment by danmichaelo** [comment]
Duplicate of #34

**Comment by danmichaelo** [comment]
CropTool should now remove {{watermark}} : https://commons.wikimedia.org/w/index.php?title=File%3ALancia_delta_1.6_GTie_engine_2.jpg&type=revision&diff=162892937&oldid=162892935

**Comment by LTeles** [comment]
Thanks!
