### ISSUE TITLE
Magic border locator removing 1 px from right side

### ISSUE THREAD

**Issue by RileyHuntley** [danmichaelo/croptool#59]
Magic border locator has the habit of wanting to remove 1 px from the right side of the image, for no apparent reason. I've cropped a batch of 200 images using CropTool, all of them were only needed 20pxs removed from the bottom, yet it constantly wanted to remove from the right side.

**Comment by RileyHuntley** [comment]
Also, is there any way to manually trigger magic border locator? (i.e. https://tools.wmflabs.org/croptool/?title=Piper_PA-28_(5743734767).jpg&action=magic)

**Comment by danmichaelo** [comment]
Now, https://tools.wmflabs.org/croptool/?title=Piper_PA-28_(5743734767).jpg&action=magic should work

Not really sure about the 1px issue. Cannot reproduce it in all cases, although I've seen it happen.

**Comment by danmichaelo** [comment]
Now i figured out the 1px issue as well. It was a real issue, but I just didn't see it on larger images because of roundoff errors.
