### ISSUE TITLE
"Upload failed"

### ISSUE THREAD

**Issue by magnusmanske** [danmichaelo/croptool#60]
Trying to crop "Rebbie" from Jacksonstvshow.jpg
Original: 790 x 1253 px. Crop: 299 x 866 px.
Trying to upload as new file "Rebbie Jackson.jpg"
Clicking on Upload => "Upload failed!", no details.
JS console prints objects with "was-deleted" warning.

Upload as "Rebbie Jackson 2.jpg" was successful.

Suggestion: When object (let's call it "o") has o.result = "Warning", show the keys of the o.warnings object as text.

**Comment by danmichaelo** [comment]
> Suggestion: When object (let's call it "o") has o.result = "Warning", show the keys of the o.warnings object as text.

Yeah, should definitely do that.

And once the user is presented the warning, I guess it could also make sense to give him/her some way of retrying the upload with `ignorewarnings`.

**Comment by magnusmanske** [comment]
Depending on the warning, this could actually happen automatically. Just because a file with that name has been deleted before, the new cropped one is likely perfectly legit. Other reasons ("file exists" etc.) would require user confirmation, or should be prohibited altogether. "File exists" could be checked before anyway, maybe even while typing.
Yay interface work!

**Comment by danmichaelo** [comment]
Always fun.. 

Yeah, agree that the 'was-deleted' warning can really be ignored automatically. And it's probably a good idea to prohibit ignoring of 'file exists'. And for other warnings, we can show the warning(s) and allow ignoring.

Btw. it already checks if the file exists while typing, but it's only indicated by the input field getting a red frame if it exists.
