### ISSUE TITLE
Halt when image is unreviewed

### ISSUE THREAD

**Issue by owcz** [danmichaelo/croptool#67]
The most populous subset of images in "Category:Flickr images needing human review" were cropped in Croptool. It would be nice if the tool would prevent overwriting the original image while a {{flickrreview}} tag still stands. (If the user just waits a few minutes, the tool does its verification and they can crop to their heart's content.) Otherwise the bot trips up and a human reviewer needs to go manually verify the image, which is a waste of everyone's time.

**Comment by danmichaelo** [comment]
Implemented!

**Comment by danmichaelo** [comment]
Test images here: https://commons.wikimedia.org/wiki/Category:Flickr_review_needed

**Comment by owcz** [comment]
I currently get [a mess](https://www.dropbox.com/s/tgfiicfezuvuzy6/Screenshot%202015-06-12%2009.13.41.png?dl=0) when I go to crop any image in that category. Bug?

**Comment by danmichaelo** [comment]
Wrong screenshot ;) I would guess a cache issue.. I don't have any cache busting techniques implemented atm.

**Comment by owcz** [comment]
(Fixed the link.) I don't know what it is, but that's what I see even at https://tools.wmflabs.org/croptool/ and I can't logout or reset it.

**Comment by danmichaelo** [comment]
I'm quite sure that's a cache issue (old javascript files). Did you try (force) refreshing the page using ctrl/cmd-r or ctrl/cmd-shift-r?

**Comment by owcz** [comment]
Aaaand that did the trick. And the implementation works great—thank you!
