### ISSUE TITLE
Croptool not authenticating

### ISSUE THREAD

**Issue by nimbhharat** [danmichaelo/croptool#68]
Hi @danmichaelo 
I have a problem with CropTool. I have been using this feature since 2015 without any problems, but unexpectedly today, I have not been able to crop any images. When I logged out to refresh it, the feature would not allow me to reauthenticate. Could you please figure out what the problem is.

Your feedback is much appreciated,
Nim Bhharathhan

**Comment by danmichaelo** [comment]
Hi, thanks for reporting this. I can reproduce the problem. Will update when I have a fix or more info.

**Comment by danmichaelo** [comment]
Fix deployed and tested.
