### ISSUE TITLE
Quality Images

### ISSUE THREAD

**Issue by MartinThoma** [danmichaelo/croptool#69]
Currently, CropTool copies all of the content. This is an issue, as the crop of a quality image is not necessarily a quality image. (See https://commons.wikimedia.org/wiki/User_talk:McGeddon#Self-adding_of_QI-Label)

**Comment by danmichaelo** [comment]
I'm already skipping license review templates (#41), so it shouldn't be a problem to skip quality image templates as well. Is it just one template, or several?

**Comment by MartinThoma** [comment]
The following templates should not be transferred:

    {{QualityImage}}
    {{picture of the day}}
    {{Assessments}}

There might be more, but those are the ones I'm aware of.

**Comment by danmichaelo** [comment]
Ok, it should now skip those, plus `{{featured picture}}`, unless I've messed up the regexp.
