### ISSUE TITLE
jpegtran fails with code 1 for some files

### ISSUE THREAD

**Issue by zhuyifei1999** [danmichaelo/croptool#75]
https://commons.wikimedia.org/w/index.php?title=Commons:Village_pump&oldid=204862873#Crop_Tool

```
[Error] Command "/data/project/croptool/jpeg-9a/jpegtran -copy all -crop '1212x1833+1611+903' '/data/project/croptool/public_html/files/404851b935ceea1fd87b9d836360e40d6385a49e.jpg' > '/data/project/croptool/public_html/files/404851b935ceea1fd87b9d836360e40d6385a49e_cropped.jpg' 2>&1" exited with code 1: 1
```

**Comment by danmichaelo** [comment]
Thanks for reporting here. I can reproduce the problem with https://tools.wmflabs.org/croptool/?site=commons.wikimedia.org&title=66+Sunbeam+Tiger+(5886532478).jpg . The file has `jpeg:sampling-factor: 2x1,1x1,1x1` and `exif:Orientation: 8`, so my guess is it's related to one of those, I'll investigate.
