### ISSUE TITLE
Handle question mark in file name

### ISSUE THREAD

**Issue by owcz** [danmichaelo/croptool#87]
Tool won't open this file: https://commons.wikimedia.org/wiki/File:A._O._Scott_-_%C2%BFC%C3%B3mo_pensar_el_arte,_el_placer,_la_belleza_y_la_verdad%3F_DEL1429_(29424113753).jpg

Error: `File doesn't exist: A. O. Scott - ¿Cómo pensar el arte, el placer, la belleza y la verdad`

**Comment by danmichaelo** [comment]
Should work now
