### ISSUE TITLE
Fails if template:Crop for Wikidata bears two parameters

### ISSUE THREAD

**Issue by Laddo1** [danmichaelo/croptool#93]
On [https://commons.wikimedia.org/wiki/File:2006_World_University_Cycling_Championship.jpg this file], template {{Crop for Wikidata|Q16218635|Person on left (silver medal)}} results in CropTool message:

[Error] [api] Received error: no-such-entity : Could not find such an entity. (Invalid id: Person on left (silver medal)) 

CropTool seems not to parse the Qitem number properly.

**Comment by danmichaelo** [comment]
Think it should be fixed now.
