### ISSUE TITLE
Support tiff

### ISSUE THREAD

**Issue by danmichaelo** [danmichaelo/croptool#95]
As suggested on nowiki.

Example image: https://commons.wikimedia.org/wiki/File:Pernilla_Stalfelt_2012-02-24_002.tiff

**Comment by Sadads** [comment]
I have been using this tool a lot lately to support files for Wikidata and the #visiblewikiwomen campaign: but without tiffs.

**Comment by danmichaelo** [comment]
Also https://phabricator.wikimedia.org/T169183

**Comment by danmichaelo** [comment]
Ok, so I activated support for TIFF files. 

Example file that can be cropped correctly: https://commons.wikimedia.org/wiki/File:Ebola_Virus_-_Electron_Micrograph.tiff

TIFF is a complex format though, and I don't expect that CropTool will support all kinds of complex cases.

Here's one files that does not crop correctly: https://commons.wikimedia.org/wiki/File:Psalm_44.tiff (it has two layers/pages with different size)

**Comment by danmichaelo** [comment]
Added a page selector (same as used with DJVU and PDF), so now the latter file should also crop correctly.
