### ISSUE TITLE
Crash during initialization when aspect ratio state set to "keep"

### ISSUE THREAD

**Issue by daylenca** [danmichaelo/croptool#97]
![2017-07-08_1253](https://user-images.githubusercontent.com/10361755/27988680-a091327c-63dc-11e7-8833-7727b76a569d.png)

**Comment by danmichaelo** [comment]
Hm. You haven't disabled JavaScript? Do you have the chance to open [F12 Developer Tools](https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide) and copy any error message you might see in the [Console](https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide#the-console-tool-ctrl2)? If there's no error messages there, try reloading the page while the developer tools are open.

**Comment by daylenca** [comment]
@danmichaelo Here you are
![crop tool error on edge](https://user-images.githubusercontent.com/10361755/28000112-94b354ec-64d8-11e7-9930-5e43eef98d65.png)

**Comment by danmichaelo** [comment]
Thanks for the error! As you might have noticed, CropTool stores the last used aspect ratio setting.. The crash only happened if aspect ratio was stored as "keep", which was why I didn't see it at first, but now I found the error quite quickly. If you still have problems, try a hard reload of the page.

**Comment by daylenca** [comment]
It is working now! Thanks @danmichaelo.
