### ISSUE TITLE
Allow overwriting of other files (with warning).

### ISSUE THREAD

**Issue by bjh21** [danmichaelo/croptool#98]
When file B is a crop of file A, it would be useful if having uploaded a higher-resolution version of file A, I could use CropTool to produce a new version of file B.  However, CropTool won't overwrite the existing version of B, saying "Upload failed! File already exists: B". I had to resort to downloading the picture and cropping it using `jpegtran` myself.

**Comment by danmichaelo** [comment]
Right. This restriction was purposefully added as part of #60, but I guess it can be annoying when you know what you're doing.. Let's try removing it and see how it goes. I'm adding a checkbox to allow overwriting now:

<img width="339" alt="skjermbilde 2017-09-02 kl 20 52 23" src="https://user-images.githubusercontent.com/434495/29997981-aba091e2-9020-11e7-9c19-ca10666b77cb.png">

**Comment by bjh21** [comment]
That doesn't quite seem to work (after clicking "Upload"):
![2017-09-04t232334_tools wmflabs org](https://user-images.githubusercontent.com/631010/30039418-5ea19608-91c8-11e7-9148-6b1cf0959816.png)

**Comment by danmichaelo** [comment]
Should have tested of course... But *now* :)
